/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIInteraction {
  'feedback' : string,
  'timestamp' : Time,
  'tutorialId' : string,
}
export interface Branding {
  'icon' : [] | [ExternalBlob],
  'logo' : [] | [ExternalBlob],
  'slogan' : string,
  'siteName' : string,
}
export type ExternalBlob = Uint8Array;
export interface MediaFile {
  'contentType' : string,
  'blob' : ExternalBlob,
  'name' : string,
  'uploader' : Principal,
}
export interface Product {
  'id' : string,
  'inventory' : bigint,
  'name' : string,
  'description' : string,
  'price' : bigint,
  'images' : Array<MediaFile>,
}
export type Role = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StoreBanner {
  'title' : string,
  'bannerImage' : [] | [ExternalBlob],
  'subtitle' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TokenTransaction {
  'to' : [] | [Principal],
  'transactionType' : { 'earn' : null } |
    { 'mint' : null } |
    { 'spend' : null } |
    { 'transfer' : null },
  'from' : [] | [Principal],
  'description' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'purchasedContent' : Array<string>,
  'createdAt' : Time,
  'role' : Role,
  'aiInteractionHistory' : Array<AIInteraction>,
  'uploadedContent' : Array<MediaFile>,
  'tokenBalance' : bigint,
  'aiAssistantEnabled' : boolean,
  'transactionHistory' : Array<TokenTransaction>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<[Product], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getBlobById' : ActorMethod<[string], MediaFile>,
  'getBranding' : ActorMethod<[], Branding>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStoreBanner' : ActorMethod<[], StoreBanner>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listMedia' : ActorMethod<[], Array<MediaFile>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBranding' : ActorMethod<[Branding], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateStoreBanner' : ActorMethod<[StoreBanner], undefined>,
  'uploadMediaFile' : ActorMethod<[MediaFile], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];