/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MediaFile = IDL.Record({
  'contentType' : IDL.Text,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'uploader' : IDL.Principal,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'inventory' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
  'images' : IDL.Vec(MediaFile),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Branding = IDL.Record({
  'icon' : IDL.Opt(ExternalBlob),
  'logo' : IDL.Opt(ExternalBlob),
  'slogan' : IDL.Text,
  'siteName' : IDL.Text,
});
export const Time = IDL.Int;
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AIInteraction = IDL.Record({
  'feedback' : IDL.Text,
  'timestamp' : Time,
  'tutorialId' : IDL.Text,
});
export const TokenTransaction = IDL.Record({
  'to' : IDL.Opt(IDL.Principal),
  'transactionType' : IDL.Variant({
    'earn' : IDL.Null,
    'mint' : IDL.Null,
    'spend' : IDL.Null,
    'transfer' : IDL.Null,
  }),
  'from' : IDL.Opt(IDL.Principal),
  'description' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'purchasedContent' : IDL.Vec(IDL.Text),
  'createdAt' : Time,
  'role' : Role,
  'aiInteractionHistory' : IDL.Vec(AIInteraction),
  'uploadedContent' : IDL.Vec(MediaFile),
  'tokenBalance' : IDL.Nat,
  'aiAssistantEnabled' : IDL.Bool,
  'transactionHistory' : IDL.Vec(TokenTransaction),
});
export const StoreBanner = IDL.Record({
  'title' : IDL.Text,
  'bannerImage' : IDL.Opt(ExternalBlob),
  'subtitle' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addProduct' : IDL.Func([Product], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getBlobById' : IDL.Func([IDL.Text], [MediaFile], ['query']),
  'getBranding' : IDL.Func([], [Branding], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStoreBanner' : IDL.Func([], [StoreBanner], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listMedia' : IDL.Func([], [IDL.Vec(MediaFile)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBranding' : IDL.Func([Branding], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateStoreBanner' : IDL.Func([StoreBanner], [], []),
  'uploadMediaFile' : IDL.Func([MediaFile], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MediaFile = IDL.Record({
    'contentType' : IDL.Text,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'uploader' : IDL.Principal,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'inventory' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
    'images' : IDL.Vec(MediaFile),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Branding = IDL.Record({
    'icon' : IDL.Opt(ExternalBlob),
    'logo' : IDL.Opt(ExternalBlob),
    'slogan' : IDL.Text,
    'siteName' : IDL.Text,
  });
  const Time = IDL.Int;
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AIInteraction = IDL.Record({
    'feedback' : IDL.Text,
    'timestamp' : Time,
    'tutorialId' : IDL.Text,
  });
  const TokenTransaction = IDL.Record({
    'to' : IDL.Opt(IDL.Principal),
    'transactionType' : IDL.Variant({
      'earn' : IDL.Null,
      'mint' : IDL.Null,
      'spend' : IDL.Null,
      'transfer' : IDL.Null,
    }),
    'from' : IDL.Opt(IDL.Principal),
    'description' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'purchasedContent' : IDL.Vec(IDL.Text),
    'createdAt' : Time,
    'role' : Role,
    'aiInteractionHistory' : IDL.Vec(AIInteraction),
    'uploadedContent' : IDL.Vec(MediaFile),
    'tokenBalance' : IDL.Nat,
    'aiAssistantEnabled' : IDL.Bool,
    'transactionHistory' : IDL.Vec(TokenTransaction),
  });
  const StoreBanner = IDL.Record({
    'title' : IDL.Text,
    'bannerImage' : IDL.Opt(ExternalBlob),
    'subtitle' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addProduct' : IDL.Func([Product], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getBlobById' : IDL.Func([IDL.Text], [MediaFile], ['query']),
    'getBranding' : IDL.Func([], [Branding], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStoreBanner' : IDL.Func([], [StoreBanner], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listMedia' : IDL.Func([], [IDL.Vec(MediaFile)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBranding' : IDL.Func([Branding], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateStoreBanner' : IDL.Func([StoreBanner], [], []),
    'uploadMediaFile' : IDL.Func([MediaFile], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };