/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIFeedback {
  'feedback' : string,
  'videoTimestamp' : bigint,
  'tutorialId' : string,
}
export interface AIInteraction {
  'feedback' : string,
  'timestamp' : Time,
  'tutorialId' : string,
}
export interface AIRequest {
  'userAnswers' : Array<string>,
  'videoTimestamp' : bigint,
  'tutorialId' : string,
}
export interface AIResponse {
  'suggestions' : Array<string>,
  'feedback' : string,
}
export interface ChatMessage {
  'isAI' : boolean,
  'sender' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface CommunityPost {
  'id' : string,
  'media' : Array<MediaFile>,
  'title' : string,
  'content' : string,
  'createdAt' : Time,
  'author' : Principal,
  'likes' : bigint,
}
export type Difficulty = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export type ExternalBlob = Uint8Array;
export interface MediaFile {
  'contentType' : string,
  'blob' : ExternalBlob,
  'name' : string,
  'uploader' : Principal,
}
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'total' : bigint,
  'createdAt' : Time,
  'user' : Principal,
  'products' : Array<OrderedProduct>,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null };
export interface OrderedProduct {
  'id' : string,
  'name' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface Product {
  'id' : string,
  'inventory' : bigint,
  'name' : string,
  'description' : string,
  'price' : bigint,
  'images' : Array<MediaFile>,
}
export type Role = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StreamedContent {
  'id' : string,
  'media' : MediaFile,
  'title' : string,
  'creator' : Principal,
  'createdAt' : Time,
  'category' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TokenTransaction {
  'to' : [] | [Principal],
  'transactionType' : { 'earn' : null } |
    { 'mint' : null } |
    { 'spend' : null } |
    { 'transfer' : null },
  'from' : [] | [Principal],
  'description' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface Tutorial {
  'id' : string,
  'title' : string,
  'creator' : Principal,
  'video' : MediaFile,
  'difficulty' : Difficulty,
  'createdAt' : Time,
  'description' : string,
  'isFree' : boolean,
}
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'purchasedContent' : Array<string>,
  'createdAt' : Time,
  'role' : Role,
  'aiInteractionHistory' : Array<AIInteraction>,
  'uploadedContent' : Array<MediaFile>,
  'tokenBalance' : bigint,
  'aiAssistantEnabled' : boolean,
  'transactionHistory' : Array<TokenTransaction>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addPost' : ActorMethod<[CommunityPost], string>,
  'addProduct' : ActorMethod<[Product], string>,
  'addStream' : ActorMethod<[StreamedContent], string>,
  'addTutorial' : ActorMethod<[Tutorial], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearChatHistory' : ActorMethod<[], undefined>,
  'clearMedia' : ActorMethod<[], undefined>,
  'clearTutorials' : ActorMethod<[], undefined>,
  'completeTutorial' : ActorMethod<[string], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteMedia' : ActorMethod<[string], undefined>,
  'deletePost' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteStream' : ActorMethod<[string], undefined>,
  'deleteTutorial' : ActorMethod<[string], undefined>,
  'filterTutorialsByDifficulty' : ActorMethod<[Difficulty], Array<Tutorial>>,
  'getAIFeedback' : ActorMethod<[string, bigint], [] | [AIFeedback]>,
  'getAIHistory' : ActorMethod<[Principal, string], Array<AIInteraction>>,
  'getBalance' : ActorMethod<[Principal], bigint>,
  'getBlobById' : ActorMethod<[string], MediaFile>,
  'getCallerAddress' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getStripeConfiguration' : ActorMethod<[], StripeConfiguration>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTransactionHistory' : ActorMethod<[Principal], Array<TokenTransaction>>,
  'getTutorial' : ActorMethod<[string], [] | [Tutorial]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isAIAssistantEnabled' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listMedia' : ActorMethod<[], Array<MediaFile>>,
  'listPosts' : ActorMethod<[], Array<CommunityPost>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listStreams' : ActorMethod<[], Array<StreamedContent>>,
  'listTutorials' : ActorMethod<[], Array<Tutorial>>,
  'mintTokens' : ActorMethod<[Principal, bigint, string], undefined>,
  'placeOrder' : ActorMethod<[Order], string>,
  'provideAIResponse' : ActorMethod<[AIRequest], AIResponse>,
  'recordEarning' : ActorMethod<[Principal, bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendAIChatResponse' : ActorMethod<[string], undefined>,
  'sendChatMessage' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'spendTokens' : ActorMethod<[bigint, string], undefined>,
  'toggleAIAssistant' : ActorMethod<[boolean], undefined>,
  'transferTokens' : ActorMethod<[Principal, bigint, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAIFeedback' : ActorMethod<[string, string, bigint], undefined>,
  'updateAIHistory' : ActorMethod<[Principal, AIInteraction], undefined>,
  'updateProfile' : ActorMethod<[UserProfile], string>,
  'uploadMediaFile' : ActorMethod<[MediaFile], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];