/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MediaFile = IDL.Record({
  'contentType' : IDL.Text,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'uploader' : IDL.Principal,
});
export const Time = IDL.Int;
export const CommunityPost = IDL.Record({
  'id' : IDL.Text,
  'media' : IDL.Vec(MediaFile),
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'likes' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'inventory' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
  'images' : IDL.Vec(MediaFile),
});
export const StreamedContent = IDL.Record({
  'id' : IDL.Text,
  'media' : MediaFile,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'createdAt' : Time,
  'category' : IDL.Text,
});
export const Difficulty = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const Tutorial = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'video' : MediaFile,
  'difficulty' : Difficulty,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isFree' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const AIFeedback = IDL.Record({
  'feedback' : IDL.Text,
  'videoTimestamp' : IDL.Nat,
  'tutorialId' : IDL.Text,
});
export const AIInteraction = IDL.Record({
  'feedback' : IDL.Text,
  'timestamp' : Time,
  'tutorialId' : IDL.Text,
});
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TokenTransaction = IDL.Record({
  'to' : IDL.Opt(IDL.Principal),
  'transactionType' : IDL.Variant({
    'earn' : IDL.Null,
    'mint' : IDL.Null,
    'spend' : IDL.Null,
    'transfer' : IDL.Null,
  }),
  'from' : IDL.Opt(IDL.Principal),
  'description' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'purchasedContent' : IDL.Vec(IDL.Text),
  'createdAt' : Time,
  'role' : Role,
  'aiInteractionHistory' : IDL.Vec(AIInteraction),
  'uploadedContent' : IDL.Vec(MediaFile),
  'tokenBalance' : IDL.Nat,
  'aiAssistantEnabled' : IDL.Bool,
  'transactionHistory' : IDL.Vec(TokenTransaction),
});
export const ChatMessage = IDL.Record({
  'isAI' : IDL.Bool,
  'sender' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const OrderedProduct = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'total' : IDL.Nat,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'products' : IDL.Vec(OrderedProduct),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const AIRequest = IDL.Record({
  'userAnswers' : IDL.Vec(IDL.Text),
  'videoTimestamp' : IDL.Nat,
  'tutorialId' : IDL.Text,
});
export const AIResponse = IDL.Record({
  'suggestions' : IDL.Vec(IDL.Text),
  'feedback' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addPost' : IDL.Func([CommunityPost], [IDL.Text], []),
  'addProduct' : IDL.Func([Product], [IDL.Text], []),
  'addStream' : IDL.Func([StreamedContent], [IDL.Text], []),
  'addTutorial' : IDL.Func([Tutorial], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearChatHistory' : IDL.Func([], [], []),
  'clearMedia' : IDL.Func([], [], []),
  'clearTutorials' : IDL.Func([], [], []),
  'completeTutorial' : IDL.Func([IDL.Text], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteMedia' : IDL.Func([IDL.Text], [], []),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'deleteStream' : IDL.Func([IDL.Text], [], []),
  'deleteTutorial' : IDL.Func([IDL.Text], [], []),
  'filterTutorialsByDifficulty' : IDL.Func(
      [Difficulty],
      [IDL.Vec(Tutorial)],
      ['query'],
    ),
  'getAIFeedback' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(AIFeedback)],
      ['query'],
    ),
  'getAIHistory' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Vec(AIInteraction)],
      ['query'],
    ),
  'getBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getBlobById' : IDL.Func([IDL.Text], [MediaFile], ['query']),
  'getCallerAddress' : IDL.Func([], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getStripeConfiguration' : IDL.Func([], [StripeConfiguration], []),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTransactionHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TokenTransaction)],
      ['query'],
    ),
  'getTutorial' : IDL.Func([IDL.Text], [IDL.Opt(Tutorial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isAIAssistantEnabled' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listMedia' : IDL.Func([], [IDL.Vec(MediaFile)], ['query']),
  'listPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listStreams' : IDL.Func([], [IDL.Vec(StreamedContent)], ['query']),
  'listTutorials' : IDL.Func([], [IDL.Vec(Tutorial)], ['query']),
  'mintTokens' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'placeOrder' : IDL.Func([Order], [IDL.Text], []),
  'provideAIResponse' : IDL.Func([AIRequest], [AIResponse], []),
  'recordEarning' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendAIChatResponse' : IDL.Func([IDL.Text], [], []),
  'sendChatMessage' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'spendTokens' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'toggleAIAssistant' : IDL.Func([IDL.Bool], [], []),
  'transferTokens' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAIFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'updateAIHistory' : IDL.Func([IDL.Principal, AIInteraction], [], []),
  'updateProfile' : IDL.Func([UserProfile], [IDL.Text], []),
  'uploadMediaFile' : IDL.Func([MediaFile], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MediaFile = IDL.Record({
    'contentType' : IDL.Text,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'uploader' : IDL.Principal,
  });
  const Time = IDL.Int;
  const CommunityPost = IDL.Record({
    'id' : IDL.Text,
    'media' : IDL.Vec(MediaFile),
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'likes' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'inventory' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
    'images' : IDL.Vec(MediaFile),
  });
  const StreamedContent = IDL.Record({
    'id' : IDL.Text,
    'media' : MediaFile,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'createdAt' : Time,
    'category' : IDL.Text,
  });
  const Difficulty = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const Tutorial = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'video' : MediaFile,
    'difficulty' : Difficulty,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isFree' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const AIFeedback = IDL.Record({
    'feedback' : IDL.Text,
    'videoTimestamp' : IDL.Nat,
    'tutorialId' : IDL.Text,
  });
  const AIInteraction = IDL.Record({
    'feedback' : IDL.Text,
    'timestamp' : Time,
    'tutorialId' : IDL.Text,
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TokenTransaction = IDL.Record({
    'to' : IDL.Opt(IDL.Principal),
    'transactionType' : IDL.Variant({
      'earn' : IDL.Null,
      'mint' : IDL.Null,
      'spend' : IDL.Null,
      'transfer' : IDL.Null,
    }),
    'from' : IDL.Opt(IDL.Principal),
    'description' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'purchasedContent' : IDL.Vec(IDL.Text),
    'createdAt' : Time,
    'role' : Role,
    'aiInteractionHistory' : IDL.Vec(AIInteraction),
    'uploadedContent' : IDL.Vec(MediaFile),
    'tokenBalance' : IDL.Nat,
    'aiAssistantEnabled' : IDL.Bool,
    'transactionHistory' : IDL.Vec(TokenTransaction),
  });
  const ChatMessage = IDL.Record({
    'isAI' : IDL.Bool,
    'sender' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const OrderedProduct = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'total' : IDL.Nat,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'products' : IDL.Vec(OrderedProduct),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const AIRequest = IDL.Record({
    'userAnswers' : IDL.Vec(IDL.Text),
    'videoTimestamp' : IDL.Nat,
    'tutorialId' : IDL.Text,
  });
  const AIResponse = IDL.Record({
    'suggestions' : IDL.Vec(IDL.Text),
    'feedback' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addPost' : IDL.Func([CommunityPost], [IDL.Text], []),
    'addProduct' : IDL.Func([Product], [IDL.Text], []),
    'addStream' : IDL.Func([StreamedContent], [IDL.Text], []),
    'addTutorial' : IDL.Func([Tutorial], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearChatHistory' : IDL.Func([], [], []),
    'clearMedia' : IDL.Func([], [], []),
    'clearTutorials' : IDL.Func([], [], []),
    'completeTutorial' : IDL.Func([IDL.Text], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteMedia' : IDL.Func([IDL.Text], [], []),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'deleteStream' : IDL.Func([IDL.Text], [], []),
    'deleteTutorial' : IDL.Func([IDL.Text], [], []),
    'filterTutorialsByDifficulty' : IDL.Func(
        [Difficulty],
        [IDL.Vec(Tutorial)],
        ['query'],
      ),
    'getAIFeedback' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(AIFeedback)],
        ['query'],
      ),
    'getAIHistory' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Vec(AIInteraction)],
        ['query'],
      ),
    'getBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getBlobById' : IDL.Func([IDL.Text], [MediaFile], ['query']),
    'getCallerAddress' : IDL.Func([], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getStripeConfiguration' : IDL.Func([], [StripeConfiguration], []),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTransactionHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TokenTransaction)],
        ['query'],
      ),
    'getTutorial' : IDL.Func([IDL.Text], [IDL.Opt(Tutorial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isAIAssistantEnabled' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listMedia' : IDL.Func([], [IDL.Vec(MediaFile)], ['query']),
    'listPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listStreams' : IDL.Func([], [IDL.Vec(StreamedContent)], ['query']),
    'listTutorials' : IDL.Func([], [IDL.Vec(Tutorial)], ['query']),
    'mintTokens' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
    'placeOrder' : IDL.Func([Order], [IDL.Text], []),
    'provideAIResponse' : IDL.Func([AIRequest], [AIResponse], []),
    'recordEarning' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendAIChatResponse' : IDL.Func([IDL.Text], [], []),
    'sendChatMessage' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'spendTokens' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'toggleAIAssistant' : IDL.Func([IDL.Bool], [], []),
    'transferTokens' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAIFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'updateAIHistory' : IDL.Func([IDL.Principal, AIInteraction], [], []),
    'updateProfile' : IDL.Func([UserProfile], [IDL.Text], []),
    'uploadMediaFile' : IDL.Func([MediaFile], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };