/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    bio: string;
    username: string;
    purchasedContent: Array<string>;
    createdAt: Time;
    role: Role;
    aiInteractionHistory: Array<AIInteraction>;
    uploadedContent: Array<MediaFile>;
    tokenBalance: bigint;
    aiAssistantEnabled: boolean;
    transactionHistory: Array<TokenTransaction>;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface AIFeedback {
    feedback: string;
    videoTimestamp: bigint;
    tutorialId: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Tutorial {
    id: string;
    title: string;
    creator: Principal;
    video: MediaFile;
    difficulty: Difficulty;
    createdAt: Time;
    description: string;
    isFree: boolean;
}
export interface CommunityPost {
    id: string;
    media: Array<MediaFile>;
    title: string;
    content: string;
    createdAt: Time;
    author: Principal;
    likes: bigint;
}
export interface OrderedProduct {
    id: string;
    name: string;
    quantity: bigint;
    price: bigint;
}
export interface AIResponse {
    suggestions: Array<string>;
    feedback: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface AIRequest {
    userAnswers: Array<string>;
    videoTimestamp: bigint;
    tutorialId: string;
}
export interface AIInteraction {
    feedback: string;
    timestamp: Time;
    tutorialId: string;
}
export interface ChatMessage {
    isAI: boolean;
    sender: string;
    message: string;
    timestamp: Time;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface MediaFile {
    contentType: string;
    blob: ExternalBlob;
    name: string;
    uploader: Principal;
}
export interface TokenTransaction {
    to?: Principal;
    transactionType: Variant_earn_mint_spend_transfer;
    from?: Principal;
    description: string;
    timestamp: Time;
    amount: bigint;
}
export interface Order {
    id: string;
    status: OrderStatus;
    total: bigint;
    createdAt: Time;
    user: Principal;
    products: Array<OrderedProduct>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface StreamedContent {
    id: string;
    media: MediaFile;
    title: string;
    creator: Principal;
    createdAt: Time;
    category: string;
}
export interface Product {
    id: string;
    inventory: bigint;
    name: string;
    description: string;
    price: bigint;
    images: Array<MediaFile>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Difficulty {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced"
}
export enum OrderStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed"
}
export enum Role {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_earn_mint_spend_transfer {
    earn = "earn",
    mint = "mint",
    spend = "spend",
    transfer = "transfer"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addPost(post: CommunityPost): Promise<string>;
    addProduct(product: Product): Promise<string>;
    addStream(content: StreamedContent): Promise<string>;
    addTutorial(tutorial: Tutorial): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearChatHistory(): Promise<void>;
    clearMedia(): Promise<void>;
    clearTutorials(): Promise<void>;
    completeTutorial(tutorialId: string): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    deleteMedia(id: string): Promise<void>;
    deletePost(id: string): Promise<void>;
    deleteProduct(id: string): Promise<void>;
    deleteStream(id: string): Promise<void>;
    deleteTutorial(id: string): Promise<void>;
    filterTutorialsByDifficulty(difficulty: Difficulty): Promise<Array<Tutorial>>;
    getAIFeedback(tutorialId: string, timestamp: bigint): Promise<AIFeedback | null>;
    getAIHistory(user: Principal, tutorialId: string): Promise<Array<AIInteraction>>;
    getBalance(user: Principal): Promise<bigint>;
    getBlobById(id: string): Promise<MediaFile>;
    getCallerAddress(): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatHistory(): Promise<Array<ChatMessage>>;
    getOrder(orderId: string): Promise<Order | null>;
    getStripeConfiguration(): Promise<StripeConfiguration>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTransactionHistory(user: Principal): Promise<Array<TokenTransaction>>;
    getTutorial(tutorialId: string): Promise<Tutorial | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserProfiles(): Promise<Array<UserProfile>>;
    initializeAccessControl(): Promise<void>;
    isAIAssistantEnabled(user: Principal): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listMedia(): Promise<Array<MediaFile>>;
    listPosts(): Promise<Array<CommunityPost>>;
    listProducts(): Promise<Array<Product>>;
    listStreams(): Promise<Array<StreamedContent>>;
    listTutorials(): Promise<Array<Tutorial>>;
    mintTokens(recipient: Principal, amount: bigint, description: string): Promise<void>;
    placeOrder(order: Order): Promise<string>;
    provideAIResponse(request: AIRequest): Promise<AIResponse>;
    recordEarning(user: Principal, amount: bigint, description: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendAIChatResponse(message: string): Promise<void>;
    sendChatMessage(message: string): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    spendTokens(amount: bigint, description: string): Promise<void>;
    toggleAIAssistant(enabled: boolean): Promise<void>;
    transferTokens(to: Principal, amount: bigint, description: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAIFeedback(tutorialId: string, feedback: string, timestamp: bigint): Promise<void>;
    updateAIHistory(user: Principal, interaction: AIInteraction): Promise<void>;
    updateProfile(profile: UserProfile): Promise<string>;
    uploadMediaFile(media: MediaFile): Promise<string>;
}
import type { AIFeedback as _AIFeedback, AIInteraction as _AIInteraction, CommunityPost as _CommunityPost, Difficulty as _Difficulty, ExternalBlob as _ExternalBlob, MediaFile as _MediaFile, Order as _Order, OrderStatus as _OrderStatus, OrderedProduct as _OrderedProduct, Product as _Product, Role as _Role, StreamedContent as _StreamedContent, StripeSessionStatus as _StripeSessionStatus, Time as _Time, TokenTransaction as _TokenTransaction, Tutorial as _Tutorial, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addPost(arg0: CommunityPost): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addPost(await to_candid_CommunityPost_n8(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPost(await to_candid_CommunityPost_n8(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async addProduct(arg0: Product): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(await to_candid_Product_n14(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(await to_candid_Product_n14(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async addStream(arg0: StreamedContent): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addStream(await to_candid_StreamedContent_n16(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStream(await to_candid_StreamedContent_n16(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async addTutorial(arg0: Tutorial): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addTutorial(await to_candid_Tutorial_n18(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTutorial(await to_candid_Tutorial_n18(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n22(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n22(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async clearChatHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearChatHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearChatHistory();
            return result;
        }
    }
    async clearMedia(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearMedia();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearMedia();
            return result;
        }
    }
    async clearTutorials(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearTutorials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearTutorials();
            return result;
        }
    }
    async completeTutorial(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTutorial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTutorial(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteMedia(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedia(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedia(arg0);
            return result;
        }
    }
    async deletePost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteStream(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStream(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStream(arg0);
            return result;
        }
    }
    async deleteTutorial(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTutorial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTutorial(arg0);
            return result;
        }
    }
    async filterTutorialsByDifficulty(arg0: Difficulty): Promise<Array<Tutorial>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterTutorialsByDifficulty(to_candid_Difficulty_n20(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n24(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterTutorialsByDifficulty(to_candid_Difficulty_n20(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n24(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAIFeedback(arg0: string, arg1: bigint): Promise<AIFeedback | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAIFeedback(arg0, arg1);
                return from_candid_opt_n32(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAIFeedback(arg0, arg1);
            return from_candid_opt_n32(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAIHistory(arg0: Principal, arg1: string): Promise<Array<AIInteraction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAIHistory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAIHistory(arg0, arg1);
            return result;
        }
    }
    async getBalance(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance(arg0);
            return result;
        }
    }
    async getBlobById(arg0: string): Promise<MediaFile> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlobById(arg0);
                return from_candid_MediaFile_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlobById(arg0);
            return from_candid_MediaFile_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerAddress(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAddress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAddress();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n44(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n44(this.uploadFile, this.downloadFile, result);
        }
    }
    async getChatHistory(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatHistory();
            return result;
        }
    }
    async getOrder(arg0: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n45(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n45(this.uploadFile, this.downloadFile, result);
        }
    }
    async getStripeConfiguration(): Promise<StripeConfiguration> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeConfiguration();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeConfiguration();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n50(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n50(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTransactionHistory(arg0: Principal): Promise<Array<TokenTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory(arg0);
                return from_candid_vec_n39(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory(arg0);
            return from_candid_vec_n39(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTutorial(arg0: string): Promise<Tutorial | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTutorial(arg0);
                return from_candid_opt_n54(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTutorial(arg0);
            return from_candid_opt_n54(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfiles();
                return from_candid_vec_n55(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfiles();
            return from_candid_vec_n55(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isAIAssistantEnabled(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAIAssistantEnabled(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAIAssistantEnabled(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listMedia(): Promise<Array<MediaFile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMedia();
                return from_candid_vec_n38(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMedia();
            return from_candid_vec_n38(this.uploadFile, this.downloadFile, result);
        }
    }
    async listPosts(): Promise<Array<CommunityPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPosts();
                return from_candid_vec_n56(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPosts();
            return from_candid_vec_n56(this.uploadFile, this.downloadFile, result);
        }
    }
    async listProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts();
                return from_candid_vec_n59(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts();
            return from_candid_vec_n59(this.uploadFile, this.downloadFile, result);
        }
    }
    async listStreams(): Promise<Array<StreamedContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStreams();
                return from_candid_vec_n62(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStreams();
            return from_candid_vec_n62(this.uploadFile, this.downloadFile, result);
        }
    }
    async listTutorials(): Promise<Array<Tutorial>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTutorials();
                return from_candid_vec_n24(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTutorials();
            return from_candid_vec_n24(this.uploadFile, this.downloadFile, result);
        }
    }
    async mintTokens(arg0: Principal, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.mintTokens(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mintTokens(arg0, arg1, arg2);
            return result;
        }
    }
    async placeOrder(arg0: Order): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_Order_n65(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_Order_n65(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async provideAIResponse(arg0: AIRequest): Promise<AIResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.provideAIResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.provideAIResponse(arg0);
            return result;
        }
    }
    async recordEarning(arg0: Principal, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordEarning(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordEarning(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n69(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n69(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async sendAIChatResponse(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendAIChatResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendAIChatResponse(arg0);
            return result;
        }
    }
    async sendChatMessage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChatMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChatMessage(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async spendTokens(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.spendTokens(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.spendTokens(arg0, arg1);
            return result;
        }
    }
    async toggleAIAssistant(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAIAssistant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAIAssistant(arg0);
            return result;
        }
    }
    async transferTokens(arg0: Principal, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.transferTokens(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferTokens(arg0, arg1, arg2);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAIFeedback(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAIFeedback(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAIFeedback(arg0, arg1, arg2);
            return result;
        }
    }
    async updateAIHistory(arg0: Principal, arg1: AIInteraction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAIHistory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAIHistory(arg0, arg1);
            return result;
        }
    }
    async updateProfile(arg0: UserProfile): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(await to_candid_UserProfile_n69(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(await to_candid_UserProfile_n69(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async uploadMediaFile(arg0: MediaFile): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadMediaFile(await to_candid_MediaFile_n11(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadMediaFile(await to_candid_MediaFile_n11(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_CommunityPost_n57(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommunityPost): Promise<CommunityPost> {
    return await from_candid_record_n58(uploadFile, downloadFile, value);
}
function from_candid_Difficulty_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n31(uploadFile, downloadFile, value);
}
async function from_candid_ExternalBlob_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
async function from_candid_MediaFile_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaFile): Promise<MediaFile> {
    return await from_candid_record_n28(uploadFile, downloadFile, value);
}
function from_candid_OrderStatus_n48(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n49(uploadFile, downloadFile, value);
}
function from_candid_Order_n46(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n47(uploadFile, downloadFile, value);
}
async function from_candid_Product_n60(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n61(uploadFile, downloadFile, value);
}
function from_candid_Role_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n37(uploadFile, downloadFile, value);
}
async function from_candid_StreamedContent_n63(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StreamedContent): Promise<StreamedContent> {
    return await from_candid_record_n64(uploadFile, downloadFile, value);
}
function from_candid_StripeSessionStatus_n50(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n51(uploadFile, downloadFile, value);
}
function from_candid_TokenTransaction_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TokenTransaction): TokenTransaction {
    return from_candid_record_n41(uploadFile, downloadFile, value);
}
async function from_candid_Tutorial_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tutorial): Promise<Tutorial> {
    return await from_candid_record_n26(uploadFile, downloadFile, value);
}
async function from_candid_UserProfile_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n35(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n37(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AIFeedback]): AIFeedback | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n34(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n46(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n53(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n54(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tutorial]): Promise<Tutorial | null> {
    return value.length === 0 ? null : await from_candid_Tutorial_n25(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    creator: Principal;
    video: _MediaFile;
    difficulty: _Difficulty;
    createdAt: _Time;
    description: string;
    isFree: boolean;
}): Promise<{
    id: string;
    title: string;
    creator: Principal;
    video: MediaFile;
    difficulty: Difficulty;
    createdAt: Time;
    description: string;
    isFree: boolean;
}> {
    return {
        id: value.id,
        title: value.title,
        creator: value.creator,
        video: await from_candid_MediaFile_n27(uploadFile, downloadFile, value.video),
        difficulty: from_candid_Difficulty_n30(uploadFile, downloadFile, value.difficulty),
        createdAt: value.createdAt,
        description: value.description,
        isFree: value.isFree
    };
}
async function from_candid_record_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contentType: string;
    blob: _ExternalBlob;
    name: string;
    uploader: Principal;
}): Promise<{
    contentType: string;
    blob: ExternalBlob;
    name: string;
    uploader: Principal;
}> {
    return {
        contentType: value.contentType,
        blob: await from_candid_ExternalBlob_n29(uploadFile, downloadFile, value.blob),
        name: value.name,
        uploader: value.uploader
    };
}
async function from_candid_record_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    purchasedContent: Array<string>;
    createdAt: _Time;
    role: _Role;
    aiInteractionHistory: Array<_AIInteraction>;
    uploadedContent: Array<_MediaFile>;
    tokenBalance: bigint;
    aiAssistantEnabled: boolean;
    transactionHistory: Array<_TokenTransaction>;
}): Promise<{
    bio: string;
    username: string;
    purchasedContent: Array<string>;
    createdAt: Time;
    role: Role;
    aiInteractionHistory: Array<AIInteraction>;
    uploadedContent: Array<MediaFile>;
    tokenBalance: bigint;
    aiAssistantEnabled: boolean;
    transactionHistory: Array<TokenTransaction>;
}> {
    return {
        bio: value.bio,
        username: value.username,
        purchasedContent: value.purchasedContent,
        createdAt: value.createdAt,
        role: from_candid_Role_n36(uploadFile, downloadFile, value.role),
        aiInteractionHistory: value.aiInteractionHistory,
        uploadedContent: await from_candid_vec_n38(uploadFile, downloadFile, value.uploadedContent),
        tokenBalance: value.tokenBalance,
        aiAssistantEnabled: value.aiAssistantEnabled,
        transactionHistory: from_candid_vec_n39(uploadFile, downloadFile, value.transactionHistory)
    };
}
function from_candid_record_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: [] | [Principal];
    transactionType: {
        earn: null;
    } | {
        mint: null;
    } | {
        spend: null;
    } | {
        transfer: null;
    };
    from: [] | [Principal];
    description: string;
    timestamp: _Time;
    amount: bigint;
}): {
    to?: Principal;
    transactionType: Variant_earn_mint_spend_transfer;
    from?: Principal;
    description: string;
    timestamp: Time;
    amount: bigint;
} {
    return {
        to: record_opt_to_undefined(from_candid_opt_n42(uploadFile, downloadFile, value.to)),
        transactionType: from_candid_variant_n43(uploadFile, downloadFile, value.transactionType),
        from: record_opt_to_undefined(from_candid_opt_n42(uploadFile, downloadFile, value.from)),
        description: value.description,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n47(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _OrderStatus;
    total: bigint;
    createdAt: _Time;
    user: Principal;
    products: Array<_OrderedProduct>;
}): {
    id: string;
    status: OrderStatus;
    total: bigint;
    createdAt: Time;
    user: Principal;
    products: Array<OrderedProduct>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n48(uploadFile, downloadFile, value.status),
        total: value.total,
        createdAt: value.createdAt,
        user: value.user,
        products: value.products
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n52(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n53(uploadFile, downloadFile, value.userPrincipal)),
        response: value.response
    };
}
async function from_candid_record_n58(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    media: Array<_MediaFile>;
    title: string;
    content: string;
    createdAt: _Time;
    author: Principal;
    likes: bigint;
}): Promise<{
    id: string;
    media: Array<MediaFile>;
    title: string;
    content: string;
    createdAt: Time;
    author: Principal;
    likes: bigint;
}> {
    return {
        id: value.id,
        media: await from_candid_vec_n38(uploadFile, downloadFile, value.media),
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        author: value.author,
        likes: value.likes
    };
}
async function from_candid_record_n61(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    inventory: bigint;
    name: string;
    description: string;
    price: bigint;
    images: Array<_MediaFile>;
}): Promise<{
    id: string;
    inventory: bigint;
    name: string;
    description: string;
    price: bigint;
    images: Array<MediaFile>;
}> {
    return {
        id: value.id,
        inventory: value.inventory,
        name: value.name,
        description: value.description,
        price: value.price,
        images: await from_candid_vec_n38(uploadFile, downloadFile, value.images)
    };
}
async function from_candid_record_n64(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    media: _MediaFile;
    title: string;
    creator: Principal;
    createdAt: _Time;
    category: string;
}): Promise<{
    id: string;
    media: MediaFile;
    title: string;
    creator: Principal;
    createdAt: Time;
    category: string;
}> {
    return {
        id: value.id,
        media: await from_candid_MediaFile_n27(uploadFile, downloadFile, value.media),
        title: value.title,
        creator: value.creator,
        createdAt: value.createdAt,
        category: value.category
    };
}
function from_candid_variant_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
}): Difficulty {
    return "intermediate" in value ? Difficulty.intermediate : "beginner" in value ? Difficulty.beginner : "advanced" in value ? Difficulty.advanced : value;
}
function from_candid_variant_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): Role {
    return "admin" in value ? Role.admin : "user" in value ? Role.user : "guest" in value ? Role.guest : value;
}
function from_candid_variant_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    earn: null;
} | {
    mint: null;
} | {
    spend: null;
} | {
    transfer: null;
}): Variant_earn_mint_spend_transfer {
    return "earn" in value ? Variant_earn_mint_spend_transfer.earn : "mint" in value ? Variant_earn_mint_spend_transfer.mint : "spend" in value ? Variant_earn_mint_spend_transfer.spend : "transfer" in value ? Variant_earn_mint_spend_transfer.transfer : value;
}
function from_candid_variant_n49(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
}): OrderStatus {
    return "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "completed" in value ? OrderStatus.completed : value;
}
function from_candid_variant_n51(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n52(uploadFile, downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tutorial>): Promise<Array<Tutorial>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Tutorial_n25(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MediaFile>): Promise<Array<MediaFile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MediaFile_n27(uploadFile, downloadFile, x)));
}
function from_candid_vec_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TokenTransaction>): Array<TokenTransaction> {
    return value.map((x)=>from_candid_TokenTransaction_n40(uploadFile, downloadFile, x));
}
async function from_candid_vec_n55(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Promise<Array<UserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfile_n34(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n56(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CommunityPost>): Promise<Array<CommunityPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CommunityPost_n57(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n59(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n60(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n62(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StreamedContent>): Promise<Array<StreamedContent>> {
    return await Promise.all(value.map(async (x)=>await from_candid_StreamedContent_n63(uploadFile, downloadFile, x)));
}
async function to_candid_CommunityPost_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommunityPost): Promise<_CommunityPost> {
    return await to_candid_record_n9(uploadFile, downloadFile, value);
}
function to_candid_Difficulty_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n21(uploadFile, downloadFile, value);
}
async function to_candid_ExternalBlob_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
async function to_candid_MediaFile_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaFile): Promise<_MediaFile> {
    return await to_candid_record_n12(uploadFile, downloadFile, value);
}
function to_candid_OrderStatus_n67(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n68(uploadFile, downloadFile, value);
}
function to_candid_Order_n65(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Order): _Order {
    return to_candid_record_n66(uploadFile, downloadFile, value);
}
async function to_candid_Product_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): Promise<_Product> {
    return await to_candid_record_n15(uploadFile, downloadFile, value);
}
function to_candid_Role_n71(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n23(uploadFile, downloadFile, value);
}
async function to_candid_StreamedContent_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StreamedContent): Promise<_StreamedContent> {
    return await to_candid_record_n17(uploadFile, downloadFile, value);
}
function to_candid_TokenTransaction_n73(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TokenTransaction): _TokenTransaction {
    return to_candid_record_n74(uploadFile, downloadFile, value);
}
async function to_candid_Tutorial_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tutorial): Promise<_Tutorial> {
    return await to_candid_record_n19(uploadFile, downloadFile, value);
}
async function to_candid_UserProfile_n69(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n70(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n23(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
async function to_candid_record_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contentType: string;
    blob: ExternalBlob;
    name: string;
    uploader: Principal;
}): Promise<{
    contentType: string;
    blob: _ExternalBlob;
    name: string;
    uploader: Principal;
}> {
    return {
        contentType: value.contentType,
        blob: await to_candid_ExternalBlob_n13(uploadFile, downloadFile, value.blob),
        name: value.name,
        uploader: value.uploader
    };
}
async function to_candid_record_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    inventory: bigint;
    name: string;
    description: string;
    price: bigint;
    images: Array<MediaFile>;
}): Promise<{
    id: string;
    inventory: bigint;
    name: string;
    description: string;
    price: bigint;
    images: Array<_MediaFile>;
}> {
    return {
        id: value.id,
        inventory: value.inventory,
        name: value.name,
        description: value.description,
        price: value.price,
        images: await to_candid_vec_n10(uploadFile, downloadFile, value.images)
    };
}
async function to_candid_record_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    media: MediaFile;
    title: string;
    creator: Principal;
    createdAt: Time;
    category: string;
}): Promise<{
    id: string;
    media: _MediaFile;
    title: string;
    creator: Principal;
    createdAt: _Time;
    category: string;
}> {
    return {
        id: value.id,
        media: await to_candid_MediaFile_n11(uploadFile, downloadFile, value.media),
        title: value.title,
        creator: value.creator,
        createdAt: value.createdAt,
        category: value.category
    };
}
async function to_candid_record_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    creator: Principal;
    video: MediaFile;
    difficulty: Difficulty;
    createdAt: Time;
    description: string;
    isFree: boolean;
}): Promise<{
    id: string;
    title: string;
    creator: Principal;
    video: _MediaFile;
    difficulty: _Difficulty;
    createdAt: _Time;
    description: string;
    isFree: boolean;
}> {
    return {
        id: value.id,
        title: value.title,
        creator: value.creator,
        video: await to_candid_MediaFile_n11(uploadFile, downloadFile, value.video),
        difficulty: to_candid_Difficulty_n20(uploadFile, downloadFile, value.difficulty),
        createdAt: value.createdAt,
        description: value.description,
        isFree: value.isFree
    };
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n66(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: OrderStatus;
    total: bigint;
    createdAt: Time;
    user: Principal;
    products: Array<OrderedProduct>;
}): {
    id: string;
    status: _OrderStatus;
    total: bigint;
    createdAt: _Time;
    user: Principal;
    products: Array<_OrderedProduct>;
} {
    return {
        id: value.id,
        status: to_candid_OrderStatus_n67(uploadFile, downloadFile, value.status),
        total: value.total,
        createdAt: value.createdAt,
        user: value.user,
        products: value.products
    };
}
async function to_candid_record_n70(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    purchasedContent: Array<string>;
    createdAt: Time;
    role: Role;
    aiInteractionHistory: Array<AIInteraction>;
    uploadedContent: Array<MediaFile>;
    tokenBalance: bigint;
    aiAssistantEnabled: boolean;
    transactionHistory: Array<TokenTransaction>;
}): Promise<{
    bio: string;
    username: string;
    purchasedContent: Array<string>;
    createdAt: _Time;
    role: _Role;
    aiInteractionHistory: Array<_AIInteraction>;
    uploadedContent: Array<_MediaFile>;
    tokenBalance: bigint;
    aiAssistantEnabled: boolean;
    transactionHistory: Array<_TokenTransaction>;
}> {
    return {
        bio: value.bio,
        username: value.username,
        purchasedContent: value.purchasedContent,
        createdAt: value.createdAt,
        role: to_candid_Role_n71(uploadFile, downloadFile, value.role),
        aiInteractionHistory: value.aiInteractionHistory,
        uploadedContent: await to_candid_vec_n10(uploadFile, downloadFile, value.uploadedContent),
        tokenBalance: value.tokenBalance,
        aiAssistantEnabled: value.aiAssistantEnabled,
        transactionHistory: to_candid_vec_n72(uploadFile, downloadFile, value.transactionHistory)
    };
}
function to_candid_record_n74(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to?: Principal;
    transactionType: Variant_earn_mint_spend_transfer;
    from?: Principal;
    description: string;
    timestamp: Time;
    amount: bigint;
}): {
    to: [] | [Principal];
    transactionType: {
        earn: null;
    } | {
        mint: null;
    } | {
        spend: null;
    } | {
        transfer: null;
    };
    from: [] | [Principal];
    description: string;
    timestamp: _Time;
    amount: bigint;
} {
    return {
        to: value.to ? candid_some(value.to) : candid_none(),
        transactionType: to_candid_variant_n75(uploadFile, downloadFile, value.transactionType),
        from: value.from ? candid_some(value.from) : candid_none(),
        description: value.description,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
async function to_candid_record_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    media: Array<MediaFile>;
    title: string;
    content: string;
    createdAt: Time;
    author: Principal;
    likes: bigint;
}): Promise<{
    id: string;
    media: Array<_MediaFile>;
    title: string;
    content: string;
    createdAt: _Time;
    author: Principal;
    likes: bigint;
}> {
    return {
        id: value.id,
        media: await to_candid_vec_n10(uploadFile, downloadFile, value.media),
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        author: value.author,
        likes: value.likes
    };
}
function to_candid_variant_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} {
    return value == Difficulty.intermediate ? {
        intermediate: null
    } : value == Difficulty.beginner ? {
        beginner: null
    } : value == Difficulty.advanced ? {
        advanced: null
    } : value;
}
function to_candid_variant_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.user ? {
        user: null
    } : value == Role.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n68(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} {
    return value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n75(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_earn_mint_spend_transfer): {
    earn: null;
} | {
    mint: null;
} | {
    spend: null;
} | {
    transfer: null;
} {
    return value == Variant_earn_mint_spend_transfer.earn ? {
        earn: null
    } : value == Variant_earn_mint_spend_transfer.mint ? {
        mint: null
    } : value == Variant_earn_mint_spend_transfer.spend ? {
        spend: null
    } : value == Variant_earn_mint_spend_transfer.transfer ? {
        transfer: null
    } : value;
}
async function to_candid_vec_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MediaFile>): Promise<Array<_MediaFile>> {
    return await Promise.all(value.map(async (x)=>await to_candid_MediaFile_n11(uploadFile, downloadFile, x)));
}
function to_candid_vec_n72(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TokenTransaction>): Array<_TokenTransaction> {
    return value.map((x)=>to_candid_TokenTransaction_n73(uploadFile, downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
